### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by katuki0120** [katuki0120/chat-space#10]
# IPアドレス
52.69.130.151

**Comment by yasunamiura** [comment]
林さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①サイドバーにあるグループ名と最新メッセージの下線をなくしましょう
②縮小してもボタンがずれないようにしましょう
![ChatSpace_と_Hyper](https://user-images.githubusercontent.com/52514431/80775011-6ccf3f00-8b99-11ea-8dde-cb8a32db29a4.png)
**

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by katuki0120** [comment]
①、②共に修正完了しました。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、①については修正が確認できました！
②については引き続き、ずれて表示されておりますので、再度ご確認と修正をお願いいたします。
（デプロイがうまくいっていない可能性もありますので、本番環境にて、ご確認ください＾＾）

[修正箇所]
**②縮小してもボタンがずれないようにしましょう**

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by katuki0120** [comment]
②の方、本番環境にて確認してから提出しています。
一応、デプロイをもう一度したので確認お願いします。

もし、ズレていたら画像も貼っていただけると助かります。

**Comment by naru6117** [comment]
再度ご提出ありがとうございます！

再度確認したところ、下記のようにズレて表示されました。
![スクリーンショット 2020-05-01 19 19 13](https://user-images.githubusercontent.com/49669977/80799031-bdb65600-8be0-11ea-93a6-77fca2092c6e.png)

上記箇所の修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by katuki0120** [comment]
何度もすみませんがもう一度確認お願いします。

本番環境で確認したGIFです↓
https://gyazo.com/e5bfd6cb4491b59c00581e0ccdf8c69f

**Comment by naru6117** [comment]
ご提出ありがとうございます！

再度挙動確認させて頂いたところ、やはり下記のようにずれて表示されてしまいます。
（こちらは画面を縮小しておらず、MacBookAirの13.3インチで全画面表示にした状態です）
<img width="1440" alt="スクリーンショット 2020-05-01 19 33 09" src="https://user-images.githubusercontent.com/49669977/80799924-18e94800-8be3-11ea-9c2f-655ad7592bf8.png">

恐れ入りますが、コネクト等も活用し、再度修正をお願いいたします。

修正完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by katuki0120** [comment]
再度修正しました。
別PCを使い確認したので修正されているはずです。

**Comment by keisukekodama** [comment]
修正ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
